// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MasterMemory.GeneratorCore
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class MemoryDatabaseTemplate : MemoryDatabaseTemplateBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("// <auto-generated />\n#pragma warning disable\n#nullable enable\n\n");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(Using));
            
            #line default
            #line hidden
            this.Write("\n\nnamespace ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\n{\n   public sealed class ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" : MemoryDatabaseBase\n   {\n");
 foreach(var item in GenerationContexts) { 
            this.Write("        public ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ClassName));
            
            #line default
            #line hidden
            this.Write("Table ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ClassName));
            
            #line default
            #line hidden
            this.Write("Table { get; private set; } = default!;\n");
 } 
            this.Write("\n        public ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("(\n");
 for(var i = 0; i < GenerationContexts.Length; i++) { var item = GenerationContexts[i]; 
            this.Write("            ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ClassName));
            
            #line default
            #line hidden
            this.Write("Table ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ClassName));
            
            #line default
            #line hidden
            this.Write("Table");
            
            this.Write(this.ToStringHelper.ToStringWithCulture((i == GenerationContexts.Length - 1) ? "" : ","));
            
            #line default
            #line hidden
            this.Write("\n");
 } 
            this.Write("        )\n        {\n");
 for(var i = 0; i < GenerationContexts.Length; i++) { var item = GenerationContexts[i]; 
            this.Write("            this.");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ClassName));
            
            #line default
            #line hidden
            this.Write("Table = ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ClassName));
            
            #line default
            #line hidden
            this.Write("Table;\n");
 } 
            this.Write("        }\n\n        public ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("(byte[] databaseBinary, bool internString = true, MessagePack.IFormatterResolver? formatterResolver = null, int maxDegreeOfParallelism = 1)\n            : base(databaseBinary, internString, formatterResolver, maxDegreeOfParallelism)\n        {\n        }\n\n        protected override void Init(Dictionary<string, (int offset, int count)> header, System.ReadOnlyMemory<byte> databaseBinary, MessagePack.MessagePackSerializerOptions options, int maxDegreeOfParallelism)\n        {\n            if (maxDegreeOfParallelism == 1)\n            {\n                InitSequential(header, databaseBinary, options, maxDegreeOfParallelism);\n            }\n            else\n            {\n                InitParallel(header, databaseBinary, options, maxDegreeOfParallelism);\n            }\n        }\n\n        void InitSequential(Dictionary<string, (int offset, int count)> header, System.ReadOnlyMemory<byte> databaseBinary, MessagePack.MessagePackSerializerOptions options, int maxDegreeOfParallelism)\n        {\n");
 foreach(var item in GenerationContexts) { 
            this.Write("            this.");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ClassName));
            
            #line default
            #line hidden
            this.Write("Table = ExtractTableData<");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ClassName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ClassName));
            
            #line default
            #line hidden
            this.Write("Table>(header, databaseBinary, options, xs => new ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ClassName));
            
            #line default
            #line hidden
            this.Write("Table(this, xs));\n");
 } 
            this.Write("        }\n\n        void InitParallel(Dictionary<string, (int offset, int count)> header, System.ReadOnlyMemory<byte> databaseBinary, MessagePack.MessagePackSerializerOptions options, int maxDegreeOfParallelism)\n        {\n            var extracts = new Action[]\n            {\n");
 foreach(var item in GenerationContexts) { 
            this.Write("                () => this.");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ClassName));
            
            #line default
            #line hidden
            this.Write("Table = ExtractTableData<");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ClassName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ClassName));
            
            #line default
            #line hidden
            this.Write("Table>(header, databaseBinary, options, xs => new ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ClassName));
            
            #line default
            #line hidden
            this.Write("Table(this, xs)),\n");
 } 
            this.Write("            };\n\n            System.Threading.Tasks.Parallel.Invoke(new System.Threading.Tasks.ParallelOptions\n            {\n                MaxDegreeOfParallelism = maxDegreeOfParallelism\n            }, extracts);\n        }\n\n        public ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(PrefixClassName));
            
            #line default
            #line hidden
            this.Write("ImmutableBuilder ToImmutableBuilder()\n        {\n            return new ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(PrefixClassName));
            
            #line default
            #line hidden
            this.Write("ImmutableBuilder(this);\n        }\n\n        public ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(PrefixClassName));
            
            #line default
            #line hidden
            this.Write("DatabaseBuilder ToDatabaseBuilder()\n        {\n            var builder = new ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(PrefixClassName));
            
            #line default
            #line hidden
            this.Write("DatabaseBuilder();\n");
 foreach(var item in GenerationContexts) { 
            this.Write("            builder.Append(this.");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ClassName));
            
            #line default
            #line hidden
            this.Write("Table.GetRawDataUnsafe());\n");
 } 
            this.Write("            return builder;\n        }\n\n        public ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(PrefixClassName));
            
            #line default
            #line hidden
            this.Write("DatabaseBuilder ToDatabaseBuilder(MessagePack.IFormatterResolver resolver)\n        {\n            var builder = new ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(PrefixClassName));
            
            #line default
            #line hidden
            this.Write("DatabaseBuilder(resolver);\n");
 foreach(var item in GenerationContexts) { 
            this.Write("            builder.Append(this.");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ClassName));
            
            #line default
            #line hidden
            this.Write("Table.GetRawDataUnsafe());\n");
 } 
            this.Write("            return builder;\n        }\n\n#if !DISABLE_MASTERMEMORY_VALIDATOR\n\n        public ValidateResult Validate()\n        {\n            var result = new ValidateResult();\n            var database = new ValidationDatabase(new object[]\n            {\n");
 foreach(var item in GenerationContexts) { 
            this.Write("                ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ClassName));
            
            #line default
            #line hidden
            this.Write("Table,\n");
 } 
            this.Write("            });\n\n");
 foreach(var item in GenerationContexts) { 
            this.Write("            ((ITableUniqueValidate)");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ClassName));
            
            #line default
            #line hidden
            this.Write("Table).ValidateUnique(result);\n            ValidateTable(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ClassName));
            
            #line default
            #line hidden
            this.Write("Table.All, database, \"");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.PrimaryKey.BuildPropertyTupleName()));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ClassName));
            
            #line default
            #line hidden
            this.Write("Table.PrimaryKeySelector, result);\n");
 } 
            this.Write("\n            return result;\n        }\n\n#endif\n\n        static MasterMemory.Meta.MetaDatabase? metaTable;\n\n        public static object? GetTable(");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" db, string tableName)\n        {\n            switch (tableName)\n            {\n");
 foreach(var item in GenerationContexts) { 
            this.Write("                case \"");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.MemoryTableName));
            
            #line default
            #line hidden
            this.Write("\":\n                    return db.");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ClassName));
            
            #line default
            #line hidden
            this.Write("Table;\n");
 } 
            this.Write("                default:\n                    return null;\n            }\n        }\n\n#if !DISABLE_MASTERMEMORY_METADATABASE\n\n        public static MasterMemory.Meta.MetaDatabase GetMetaDatabase()\n        {\n            if (metaTable != null) return metaTable;\n\n            var dict = new Dictionary<string, MasterMemory.Meta.MetaTable>();\n");
 foreach(var item in GenerationContexts) { 
            this.Write("            dict.Add(\"");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.MemoryTableName));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write(".Tables.");
            
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ClassName));
            
            #line default
            #line hidden
            this.Write("Table.CreateMetaTable());\n");
 } 
            this.Write("\n            metaTable = new MasterMemory.Meta.MetaDatabase(dict);\n            return metaTable;\n        }\n\n#endif\n    }\n}\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class MemoryDatabaseTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
